version: "3.8"

services:
  flower_mockup:
    container_name: "test"
    build:
      context: ../../
      dockerfile: ./baseimages/jetson_demo/Dockerfile
      args:
        - USER=$USER
    shm_size: "32gb"
    ports:
      - "8080:8080"
    runtime: nvidia
    volumes:
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - /proc/device-tree/chosen:/proc/device-tree/chosen
      - /sys/devices/:/sys/devices/
      - /sys/class/gpio:/sys/class/gpio
      - ../../conf:/home/$USER/project/conf:ro
      - ../../tmp:/home/$USER/project/tmp
      - ../../data:/home/$USER/project/data:ro
      - ../../data/CIFAR10:/home/$USER/project/data/CIFAR10:ro
      - ../../data/celeba:/home/$USER/project/data/celeba:ro
      - ../../exp:/home/$USER/project/exp
      - ../../models:/home/$USER/project/models:ro
      - ../../shell:/home/$USER/project/shell
      - ../../src:/home/$USER/project/src:ro
    environment:
      - DATA_ROOT=/home/$USER/project/data
      - NVIDIA_VISIBLE_DEVICES_FILE=all
    privileged: true