version: "3.8"

services:
  flower_faceverification:
    container_name: "test"
    build:
      context: ../../
      dockerfile: ./docker/gpu_machine/Dockerfile
      args:
        - USER=$USER
    shm_size: "32gb"
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                [
                  "0",
                  "1"
                ]
              capabilities: [ gpu ]
    volumes:
      - ../../exp:/home/$USER/project/exp
      - ../../shell:/home/$USER/project/shell
      - ../../conf:/home/$USER/project/conf:ro
      - ../../src/:/home/$USER/project/src/
    environment:
      - DATA_ROOT=/home/$USER/project/data

