version: "3.8"

services: 
  flower_mockup:
    container_name: "test"
    build: 
      context: ..
      dockerfile: ./baseimages/gpu_machine/Dockerfile
      args: 
        - USER=$USER
    shm_size: "32gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0:0","0:1", "0:2", "0:3", "1:0", "1:1", "1:2", "1:3", "1:4", "1:5", "1:6"]
              capabilities: [gpu]
    volumes:
      - ../shell:/home/$USER/project/shell:ro
      - ../conf:/home/$USER/project/conf:ro
      - ../src/client_app:/home/$USER/project/src/client_app:ro
      - ../src/common:/home/$USER/project/src/common:ro
      - ../src/dataset_app:/home/$USER/project/src/dataset_app:ro
      - ../src/utils:/home/$USER/project/src/utils:ro
      - ../src/models:/home/$USER/project/src/models:ro
      - ../src/server_app:/home/$USER/project/src/server_app:ro
      - ../src/simulation_app:/home/$USER/project/src/simulation_app:ro
      - ../src/tune_app:/home/$USER/project/src/tune_app:ro
      - ../src/driver.py:/home/$USER/project/src/driver.py:ro
      - ../local:/home/$USER/project/local:ro
      - ../face_verification:/home/$USER/project/face_verification:ro
      - ../data/CIFAR10/raw:/home/$USER/project/data/CIFAR10/raw:ro
      - ../data/CIFAR10/partitions:/home/$USER/project/data/CIFAR10/partitions:ro
      - ../data/celeba/img_landmarks_align_celeba:/home/$USER/project/data/celeba/img_landmarks_align_celeba:ro
      - ../data/usbcam/img_landmarks_align_celeba:/home/$USER/project/data/usbcam/img_landmarks_align_celeba:ro
      - ../data/celeba/identities:/home/$USER/project/data/celeba/identities:ro
    secrets:
      - wandb_api_key
      - gpu_uuid
    environment:
      - DATA_ROOT=/home/$USER/project/data
      - WANDB_API_KEY_FILE=/run/secrets/wandb_api_key
      - CUDA_VISIBLE_DEVICES_FILE=/run/secrets/gpu_uuid

secrets:
  wandb_api_key:
    file: ./.wandb_api_key
  gpu_uuid:
    file: ./.gpu_uuid